/joystick_control_node:
  ros__parameters:
    mapping:
      linear:
        x:
          axis: 1
          scale: 2.0
        y:
          axis: 0
          scale: 2.0
      angular:
        z:
          axis: 3
          scale: 4.0
      kick: "axis 5 < -0.8"
      chip: "button 5"
      dribbler:
        increment: "button 3"
        decrement: "button 2"
        spin: "button 4"
