/joystick_control_node:
  ros__parameters:
    mapping:
      linear:
        x:
          axis: 0
          scale: 0.01
        y:
          axis: 1
          scale: 0.01
      angular:
        z:
          axis: 3
          scale: 0.01
      kick: 5
      dribbler:
        increment: 3
        decrement: 2
        spin: 4
