# Request
int32 robot_id
int8 parameter_id

int8 PARAM_ID_VEL_PID_X=0
int8 PARAM_ID_VEL_PID_Y=1
int8 PARAM_ID_ANGULAR_VEL_PID_Z=2
int8 PARAM_ID_VEL_CGKF_ENCODER_NOISE=3
int8 PARAM_ID_VEL_CGKF_GYRO_NOISE=4
int8 PARAM_ID_VEL_CGKF_PROCESS_NOISE=5
int8 PARAM_ID_VEL_CGFK_INITIAL_COVARIANCE=6
int8 PARAM_ID_VEL_CGKF_K_MATRIX=7

---
# Response
float32[] data
bool success
string reason
