float32 field_length
float32 field_width
float32 goal_width
float32 goal_depth
float32 boundary_width
float32 defense_area_width
float32 defense_area_depth
geometry_msgs/Point32 center_circle
float32 center_circle_radius
geometry_msgs/Polygon field_corners
int32 ignore_side
int32 ignore_side_raw
FieldSidedInfo ours
FieldSidedInfo theirs

int32 IGNORE_SIDE_NONE = 0

int32 IGNORE_SIDE_OURS = 1
int32 IGNORE_SIDE_THEIRS = 2
