bool radio_connected
uint16 sequence_number
uint8 robot_revision_major
uint8 robot_revision_minor
float32 battery_level # volts
float32 battery_temperature # deg C
bool power_error
bool tipped_error
bool breakbeam_error
bool breakbeam_ball_detected
bool accelerometer_0_error
bool accelerometer_1_error
bool gyroscope_0_error
bool gyroscope_1_error
bool motor_0_general_error
bool motor_0_hall_error
bool motor_1_general_error
bool motor_1_hall_error
bool motor_2_general_error
bool motor_2_hall_error
bool motor_3_general_error
bool motor_3_hall_error
bool motor_4_general_error
bool motor_4_hall_error
bool chipper_available
bool kicker_available
float32 motor_0_temperature # deg C
float32 motor_1_temperature # deg C
float32 motor_2_temperature # deg C
float32 motor_3_temperature # deg C
float32 motor_4_temperature # deg C
float32 kicker_charge_level # volts
