#!/usr/bin/env python3

# Copyright 2026 A Team
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

r"""CLI entry point for the controls-analysis bag -> bag converter.

Thin wrapper around :func:`ateam_controls_analysis.bag_convert.main`. Reads a
recorded ExtendedTelemetry bag and writes a new bag that is a copy of the input
plus per-robot ControlsAnalysis topics (``/controls_analysis/robot{id}``) for
full-bag loading in Foxglove.

Example::

  # Copy the bag and add analysis topics for every robot present:
  ros2 run ateam_controls_analysis controls_analysis_bag_convert /path/to/game_bag

  # Add analysis topics for a subset of robots:
  ros2 run ateam_controls_analysis controls_analysis_bag_convert \\
      /path/to/game_bag --robot-ids 0 2 3
"""

from ateam_controls_analysis.bag_convert import main

if __name__ == '__main__':
    main()
