name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildAndTest:
    runs-on: ubuntu-22.04
    container: ros:humble
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/ateam_software
      - name: Install Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt-get update
          rosdep update --rosdistro=humble
          rosdep install --from-paths . --ignore-src -y
          ./src/ateam_software/ateam_ui/install_deps.sh
      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
      - name: Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-skip ateam_ui
          colcon test-result --verbose 
